### ISSUE TITLE
Recurring Jobs doesn't works

### ISSUE THREAD

**Issue by knopa** [HangfireIO/Hangfire.InMemory#14] opened 2024-08-27 14:50 UTC
Seems Recurring Jobs doesn't work well
![image](https://github.com/user-attachments/assets/84a22dee-1d81-4241-b9a9-ebf825c074a0)

**Comment by odinserj** [comment] 2024-08-28 07:56
Hi @knopa. Unfortunately can't reproduce this, any special actions required, like changing time zone or system time?

**Comment by knopa** [comment] 2024-08-28 08:59
.NET 8, Linux, UTC Timezone

I have some custom things which could affect 


Producer Setup

```
public static void SetupHangfireProducer(this IServiceCollection services, string connectionString, IWebHostEnvironment environment)
{
    services.AddHangfire((serviceProvider, hangfire) =>
    {
        var jobsSettingsConfig = serviceProvider.GetRequiredService<IOptions<JobsSettings>>();
        hangfire
            .UseDefaultCulture(CultureInfo.GetCultureInfo("en-US"))
            .SetDataCompatibilityLevel(CompatibilityLevel.Version_180)
            .UseInMemoryStorage(new InMemoryStorageOptions())
            .UseFilter(new AutomaticRetryAttribute
            {
                //to bypass 429 RU limit in cosmos db
                Attempts = 10,
                DelayInSecondsByAttemptFunc = attempt => (int)attempt * 60,
                LogEvents = true
            });

        HangfireJobsScheduler.RegisterAndRunJobs(jobsSettingsConfig.Value);
    });

    services.TryAddSingleton<IBackgroundJobFactory>(serviceProvider =>
        new ApplicationInsightsBackgroundJobFactory(new BackgroundJobFactory(serviceProvider.GetRequiredService<IJobFilterProvider>()))
    );

    services.TryAddSingleton<IBackgroundJobStateChanger>(serviceProvider =>
        new ApplicationInsightsBackgroundJobStateChanger(new BackgroundJobStateChanger(serviceProvider.GetRequiredService<IJobFilterProvider>()))
    );

    services.TryAddSingleton<IBackgroundJobPerformer>(serviceProvider =>
        new ApplicationInsightsBackgroundJobPerformer(
            new BackgroundJobPerformer(
                serviceProvider.GetRequiredService<IJobFilterProvider>(),
                serviceProvider.GetRequiredService<JobActivator>(),
                TaskScheduler.Default
            ),
            serviceProvider.GetRequiredService<TelemetryClient>()
        )
    );
}
```

Consumer Setup

```
public static void SetupHangfireConsumer(this IServiceCollection services, HangfireSettings config, IWebHostEnvironment environment)
{
    JobFilterProviders.Providers.Add(new HangfireJobFilterProvider());

    var hangfireOptions = Action<BackgroundJobServerOptions> (string[] queues, string name, int workerCount) =>
    {
        var envName = environment.IsProduction()
                        ? string.Empty
                        : $"{environment.EnvironmentName}-";
        return x =>
        {
            x.Queues = queues;
            x.WorkerCount = workerCount;
            x.ServerName = $"{envName}{name}-{AppVersionService.AppVersion}";
        };
    };

    services.AddHangfireServer(hangfireOptions(new[]
    {
        HangfireSettings.DefaultQueueName,
        HangfireSettings.SettingQueueName
    }, "default", config.DefaultWorkersCount));

    services.AddHangfireServer(hangfireOptions(new[]
    {
        HangfireSettings.FullSyncListQueueName
    }, "full-sync", config.FullSyncWorkersCount));

    services.AddHangfireServer(hangfireOptions(new[]
    {
        HangfireSettings.DraftQueueName
    }, "draft", config.DraftSyncWorkersCount));

    services.AddHangfireServer(hangfireOptions(new[]
    {
        HangfireSettings.SyncMessageDetailsQueueName
    }, "message-details", config.FullSyncWorkersCount));

    services.AddHangfireServer(hangfireOptions(new[]
    {
        HangfireSettings.SyncMessageWatchDetailsQueueName
    }, "watch-details", config.WatchSyncWorkersCount));

    services.AddHangfireServer(hangfireOptions(new[]
    {
        HangfireSettings.HistoryQueueName
    }, "history-messages", config.HistorySyncWorkersCount));
}
```

**Comment by knopa** [comment] 2024-08-28 09:03
If it doesn't help I will try to setup test project to reproduce that issue

**Comment by odinserj** [comment] 2024-08-29 08:05
Unlikely these additional configuration options cause this behavior. It's more likely that the [`MonotonicTime`](https://github.com/HangfireIO/Hangfire.InMemory/blob/main/src/Hangfire.InMemory/State/MonotonicTime.cs) class implementation that's used to ensure system clock drifts don't affect anything, doesn't handle some scenarios, due to differences between platforms (both .NET or OS). Unfortunately I wasn't able to replicate this behavior neither on Windows, nor on Ubuntu, so don't know what to do.

 The only solution I see is to provide another option to use `DateTime.UtcNow` as an alternative time source for such scenarios.

**Comment by odinserj** [comment] 2024-08-29 08:32
It is also strange that these recurring jobs are triggered by the recurring job schedule, since they are in the past and should be triggered. What does the [stdump](https://github.com/HangfireIO/stdump) says about your threads?

**Comment by knopa** [comment] 2024-08-29 08:57
As I see there is no real difference in MonotonicTime. I have rollback to 0.9.0 where it works fine.
https://github.com/HangfireIO/Hangfire.InMemory/compare/v0.9.0...v0.10.3

I will revert to 0.10.3 on test env and will check stdump

**Comment by knopa** [comment] 2024-08-30 15:46
So my test env shows next I deployed 0.10.3 yesterday 1:16 PM it works fine over 24 hours
![image](https://github.com/user-attachments/assets/b03645ef-df10-41e6-9bda-f62471d111f6)

Today seems it broke 4 hours ago, so for proper testing need to wait for reproduce
![image](https://github.com/user-attachments/assets/f969375a-9365-43c1-988b-bbcf9a029479)


here is stdump output
https://gist.github.com/knopa/ab2a0f1da8c9f8cec9e65dce9c9b67a7

**Comment by odinserj** [comment] 2024-09-05 09:22
Thanks @knopa! I see recurring job scheduler is stuck while acquiring a lock, will investigate this and tell you when it's finished.

```
Managed stack trace:
   - [HelperMethodFrame] (System.Threading.Thread.SleepInternal) at System.Private.CoreLib.dll
   - System.Threading.Thread.Sleep(Int32) at System.Private.CoreLib.dll
   - System.Threading.SpinWait.SpinOnceCore(Int32) at System.Private.CoreLib.dll
   - Hangfire.InMemory.State.DispatcherBase`1[[System.Guid, System.Private.CoreLib]].TryAcquireLockEntry(Hangfire.Storage.JobStorageConnection, System.String, System.TimeSpan, Hangfire.InMemory.Entities.LockEntry`1<Hangfire.Storage.JobStorageConnection> ByRef) at Hangfire.InMemory.dll
   -  at 
   - Hangfire.Server.RecurringJobScheduler.Execute(Hangfire.Server.BackgroundProcessContext) at Hangfire.Core.dll
   - Hangfire.Server.BackgroundProcessDispatcherBuilder.ExecuteProcess(System.Guid, System.Object) at Hangfire.Core.dll
   - Hangfire.Processing.BackgroundExecution.Run(System.Action`2<System.Guid,System.Object>, System.Object) at Hangfire.Core.dll
   - Hangfire.Processing.BackgroundDispatcher.DispatchLoop() at Hangfire.Core.dll
   - [DebuggerU2MCatchHandlerFrame] at 
```

**Comment by odinserj** [comment] 2024-09-05 09:55
By the way, do you see any exceptions related to Hangfire in your logs?

**Comment by knopa** [comment] 2024-09-05 10:16
Nice catch

No errors related to Hangfire in Application Insights

**Comment by odinserj** [comment] 2024-09-05 10:40
I will investigate the locking code – there's a race condition, and it's pretty difficult to catch it. I think the best we can do meanwhile is to enable DEBUG logging level for Hangfire and see if there are any exceptions originating from Hangfire.InMemory. May I ask you to do this?

**Comment by knopa** [comment] 2024-09-05 11:12
Yes I will do on test env

**Comment by odinserj** [comment] 2024-09-06 08:17
Reproduced! :fire::fire::fire:

**Comment by odinserj** [comment] 2024-09-06 11:06
And a simpler example:

```csharp
using System.Collections.Concurrent;
using System.Diagnostics;

var dictionary = new ConcurrentDictionary<string, Entry>();
var started = Stopwatch.StartNew();
var key = "hello";

while (true)
{
    var parallelism = Environment.ProcessorCount;

    Parallel.For(0, parallelism, new ParallelOptions { MaxDegreeOfParallelism = parallelism }, i =>
    {
        Entry entry;
        while (true)
        {
            entry = dictionary.GetOrAdd(key, static _ => new Entry());

            lock (entry)
            {
                if (entry.Finalized) continue;
                while (entry.Acquired) Monitor.Wait(entry);
                if (entry.Finalized) continue;

                entry.Acquired = true;
                break;
            }
        }
        
        lock (entry)
        {
            entry.Acquired = false;
            entry.Finalized = true;
            
            var result = dictionary.TryRemove(key, out _);
            if (result == false) throw new InvalidOperationException("Removal failed");
            
            Monitor.PulseAll(entry);
        }
    });

    if (started.Elapsed > TimeSpan.FromSeconds(5))
    {
        Console.WriteLine($"{DateTime.Now}: still alive...");
        started = Stopwatch.StartNew();
    }
}

internal class Entry
{
    public bool Finalized;
    public bool Acquired;
}
```

**Comment by knopa** [comment] 2024-09-06 12:27
We have .NET 8

That version failes in both 6 and 8. It defenetly means that issue just hidden by Monitor things, for example if you add 2 Console.Writeline after each GetOrAdd and TryRemove your example will works in 8 too. Especially case with Remove you ignore when dictory doesn't has a key.

```cs
using System.Collections.Concurrent;
using System.Diagnostics;

var dictionary = new ConcurrentDictionary<string, Entry>();
var started = Stopwatch.StartNew();
var key = "hello";


while (true)
{
    var parallelism = Environment.ProcessorCount;

    Parallel.For(0, parallelism, new ParallelOptions { MaxDegreeOfParallelism = parallelism }, i =>
    {
        Entry entry = dictionary.GetOrAdd(key, static _ => new Entry());

        var result = dictionary.TryRemove(key, out _);
        if (result == false)
        {
            //cause we could fail also when dictionary is empty
            if (dictionary.ContainsKey(key))
            {
                throw new InvalidOperationException("Removal failed");
            }
        }
    });

    if (started.Elapsed > TimeSpan.FromSeconds(5))
    {
        Console.WriteLine($"{DateTime.Now}: still alive...");
        started = Stopwatch.StartNew();
    }
}
```

If we try to implement real safe block, I will use library to safe efforts even not async version. That code works in 8 fine

```cs
using KeyedSemaphores;
using System.Collections.Concurrent;
using System.Diagnostics;

var dictionary = new ConcurrentDictionary<string, Entry>();
var collection = new KeyedSemaphoresDictionary<string>();
var started = Stopwatch.StartNew();
var key = "hello";

while (true)
{
    var parallelism = Environment.ProcessorCount;

    Parallel.For(0, parallelism, new ParallelOptions
    {
        MaxDegreeOfParallelism = parallelism
    },
    (i, token) =>
    {
        Entry entry;

        using (collection.Lock(key))
        {
            entry = dictionary.GetOrAdd(key, static _ => new Entry());
        }

        using (collection.Lock(key))
        {
            var result = dictionary.TryRemove(key, out _);
            if (result == false)
            {
                if (dictionary.ContainsKey(key))
                {
                    throw new InvalidOperationException("Removal failed");
                }
            }
        }
    });

    if (started.Elapsed > TimeSpan.FromSeconds(5))
    {
        Console.WriteLine($"{DateTime.Now}: still alive...");
        started = Stopwatch.StartNew();
    }
}

internal class Entry
{
    public bool Finalized;
    public bool Acquired;
}
```
Seems like as .net 8 has some perfomance improvements we start receive that issue but I remember ConcurrentDictionarry are not real thread safe, so better to cover lock with more simple options and then use concurent dictionary.
I hope it helps

**Comment by odinserj** [comment] 2024-09-10 04:06
Sorry for the delayed response. Yesterday I submitted this problem as https://github.com/dotnet/runtime/issues/107525, and it was caused by PR https://github.com/dotnet/runtime/pull/82004 released with .NET 8.0 Preview 2. Today I will add a workaround for the problem by looping with `TryRemove`, until the problem is fixed in .NET itself.

**Comment by odinserj** [comment] 2024-09-10 04:09
> Seems like as .net 8 has some perfomance improvements and we start receive that issue but I remember ConcurrentDictionarry are not real thread safe, so better to cover lock with more simple options and then use concurent dictionary.

Actually it's thread safe in its internals, but some APIs like `GetOrAdd(string, Func<String, T>)` sometimes add confusion, since the `Func` itself isn't called in a lock, please see https://andrewlock.net/making-getoradd-on-concurrentdictionary-thread-safe-using-lazy/ for details. However, dictionary's internals are fully thread safe and follow the documented behavior, that's why I decided to check and re-check and submit possible issues to .NET project itself.

**Closed** 2024-09-10 04:30 UTC
Labels: bug

**Comment by odinserj** [comment] 2024-09-10 04:51
Serhii, I have just released version 0.10.4, please try upgrading and let me know if you have any issues. Thank you so much for your assistance!

**Comment by knopa** [comment] 2024-09-10 06:02
Thanks for fix. I will try it. Funny on test env issue with debug logs doesn't reproduced yet with 0.10.3.
Looks like as i mention before delay with output to console hide problem.

I mean `GetOrAdd(string, Func<String, T>)` non atomic method. IMemoryCache has same issue.

**Comment by odinserj** [comment] 2024-09-10 06:28
It's a pretty rare race condition, in my case it happened roughly once per million of lock acquisitions. You was just "lucky" enough to get this, and 6 servers just increased the probability of such an event. But this was a great report, since `ConcurrentDictionary` is a common type used in a lot of places and it's very important for this class to be bug-free.

Concurrency 🤷‍♂️

**Comment by knopa** [comment] 2024-09-11 12:36
Just FYI Debug level doesn't show any issue before issue on 0.10.3. This time took 6 days to fail

**Comment by odinserj** [comment] 2024-10-01 03:12
Hi @knopa, how the new version is going? Do you see any issues with it?

**Comment by knopa** [comment] 2024-10-01 17:16
Hi @odinserj over 20 days on tests looks works without issues. Soon will move to production and let you know.
